name: qr_stock_tracking
description: QR stock tracking mobile client
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.4.0
  mobile_scanner: ^5.1.1
  drift: ^2.29.0
  sqlite3_flutter_libs: ^0.5.40
  json_annotation: ^4.9.0
  connectivity_plus: ^6.0.1
  path_provider: ^2.1.5
  drift_flutter: ^0.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.1
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0
  drift_dev: ^2.29.0

flutter:
  uses-material-design: true

